
* Abundance Source: Riane Eisler and The Partnership Way

A big influence on my understanding of Abundance comes from the
work of the social scientist and philosopher Riane Eisler,
especially her books
- /The Partnership Way/
and her later book (which I read first)
- /Sacred Pleasure/

Eisler's books helped me understand that /Abundance/ was not
some kind of fairy-tale impractical /Utopian/ idea. It was a
fundamental part of human nature. It is just as natural for
human groups and societies to organize in non-hierarchical
partnerships which engage primarily in win-win interactions as
it is for human groups and societies to organize in dominance
hierarchies whose dominant members engage primarily in win-lose
interactions.

Real societies throughout history can be characterized by how
closely they follow the /Dominator Model/ vs. the /Partnership
Model/. Over time societies can move along this spectrum. The
questions Eisler has investigated are
1. How do societies maintain where they are on this spectrum
   over time?
2. What causes societies to move along this spectrum?

I'm going to greatly simplify Eisler's viewpoint here. I
recommend you read at least one of her books for a more complete
understanding.

Given a choice, humans prefer to cooperate, to engage in win-win
interactions.

Given a choice, we tend to build societies which are close to
the Partnership Model.

Many ancient societies throughout the world invested very little
in defensive structures like city walls or in offensive military
capabilities. Yet they maintained extensive trade networks
exchanging materials across thousands of miles. Many of our
ancestors were not barbarians, rather they lived in societies
characterized by a great degree of trust and cooperation.

The main cause of Dominator societies is conquest. When a
Dominator society conquers another society they turn the
conquered people into slaves or serfs. This creates a painful
level of inequality. No one wants to be a slave or a serf.
Inequality becomes institutionalized and grows into elaborate
hierarchies. Life becomes about advancing one's station in life,
or one's children's stations at the expense of others.
Opportunities for advancement are often through joining the
police or the military (often the same organizations). Only a
few who join such organizations will advance their ranks. Many
will lose everything. Yet as with gambling, the success of the
few is glorified and attracts plenty of new suckers, especially
those who are desperate.

A great many examples of this conversion resulted from the
Indo-European migrations and conquests around 6000 years ago.
Most of the older societies of Europe, the Middle East and
Northern India were conquered by the migrating Indo-Europeans.
Many of the pre-exiting societies which were good examples of
/Partnership Societies/ were replaced with /Dominator
Societies/.

Because human beings prefer to cooperate, /Dominator Societies/
are unstable. They can be maintained externally by continually
war as in the city states of early Mesopotamia. Or they can be
maintained by culture, by a /Dominator Paradigm/ with memes for
/Dominator Systems Maintenance/.

We can see Dominator Systems Maintenance memes in our political
system, in corporations, in any hierarchical organization,
including in many idealistic and well-intentioned organizations
- extract resources from your inferiors
- undermine your competitors
- or turn them into (temporary) allies
- curry the favors of those above you
- until you can undermine them and move up

Eisler's studies show just how insidious /Dominator Systems
Maintenance/ is
- the system must rank everyone as much as possible
      - as conventional schools do with grades and class ranks!
- anything feminine must be viewed as inferior to the masculine
      - the great insult for a male is to say that they're feminine
- children must be brutalized
      - "spare the rod and spoil the child"
      - otherwise they won't play the game!
- all spirituality will be co-opted into hierarchical religion
      - with a male sky god at the top who is quick to punish
- pleasure will be denigrated as weak
      - unless it is "earned"
      - or taken by force
