* An Example: Water Scarcity

The contexts of Abundance and Scarcity are ways of viewing the world.
They should not be confused with resource scarcity yet when some
important resource is scarce they provide very different viewpoints.

Consider water scarcity. My family comes from Hawaii where water
is never scarce, but I grew up and live in Southern California.
The media and experts regularly tell us that there is an
impending catastrophe for the entire southwestern of North
America because of the increasing scarcity of water.

The news presents regular horror stories of wells going dry and
land subsiding as ground water is extracted faster than it it is
replenished by rainfall. We also experience devastating
wildfires which are exacerbated by dry conditions.

What are some possible responses to a shortage of water? (And by
the way, everything I'm saying here could apply to any other
scarcity, not just water.)

**** Abundance in Israel: Government/Farmer Partnership

At Burning Man I was talking with some new friends from Israel
about our water problems. (No, we're not going back to talking
about Burning Man now, that just happens to be where I often
meet people and have interesting conversations!) These new
friends expressed amazement at how inefficiently we use water in
the US. Apparently they grow the same crops in Israel as we do
in California, but with /less than a tenth of the amount of
water!/ If farmers in the arid parts of North America used water
as efficiently as Israeli farmers do, there would be no
shortage, even in drought years. How do the Israeli farmers do
it, and why?

Israeli water policy began when visionaries were faced with
trying to create an agriculturally self-sufficient new nation in
an area that didn't have enough water anywhere to do what they
wanted using conventional irrigation. Israelis never viewed
water as plentiful. Israelis knew that they had to pursue water
efficiency as much as possible. Israeli farmers deployed
efficient drip-systems many years ago. More recently they have
deployed high-tech systems which measure the exact water needs
of each plant and allocate water accordingly. Israelis expect
their government and institutions to create more efficient ways
to use water and to create incentives for farmers to use those
methods. And indeed, they are actively pursuing promising ideas
of further significant efficiencies, such as advanced
greenhouses, aeroponics, etc.

**** Abundance in Bali: Horizontal Partnership

The Indonesian island of Bali has no scarcity of water by the
standards of the North American Southwest or the Middle East.
Yet they do not have enough water for all of their farmers to
plant as much wet-rice as they would like to plan, and the
expected amount of water varies year-to-year. In response,
growers all over the island have formed a cooperative called the
Water Society which collectively decide each year how much water
will be made available to each region. They government is not
involved in this decision. The Water Society has emerged as a
powerful yet relatively non-hierarchical partnership.

**** Win-Lose in California and the Southwest

The agricultural counties of California's Central Valley have
the lowest median incomes in the state. Yet California supplies
Over a third of the country's vegetables and two-thirds of the
country's fruits and nuts. Agribusiness is extremely profitable
and politically powerful.

Extraordinary amounts of government money has been allocated to
build vast irrigation canals bringing water from northern
rivers. As agriculture in California expanded and became a
politically powerful coalition, more water was diverted until it
began to stress the once-plentiful Northern rivers, leading to
the current political stalemate for an easy supply-side
solution. Periodically, cities are exhorted or legally required
to conserve water, despite California's cities using only 11% of
the state's water. San Diego County where I live is spending a
great deal of money and carbon-producing energy in a
desalination plant to supplement urban needs.

Why is there money to pump vast amounts of water long distances
and maintain extensive canal and reservoir networks yet somehow
growers can't afford to improve the efficiency of their water
use? Why is there no partnership to decide how much land can be
sustainably planted with crops with the highest water
requirements such as wet rice, alfalfa, etc.?

The strategies through the North American Southwest is
primarily win-lose political struggle pitting
- Northern districts with rivers against the arid south
- Larger growers against each other and especially against the
  smaller, less politically powerful growers.
- California Agribusiness against California Cities
- California against the neighboring states snaring the same
  rivers, canals and reservoirs.

Here's a [[https://www.newyorker.com/news/dispatch/the-biggest-potential-water-disaster-in-the-united-states][New Yorker article on the California "Water Disaster"]]
and some commentary on it by [[https://news.ycombinator.com/item?id=31367697][The Geeks at Hacker News]]. If you
read these or follow other news about this issue, try looking at
it through the lens of the dominant Paradigms as distinct from
the conventional analysis viewpoints.

** Paradigms, not wealth, determine outcomes!

Inside of the Scarcity Paradigm, a constraint, such as the
shortage of a resource, inclines the powerful to follow a
Dominator Approach, adopting win-lose strategies to allow them
to survive or even flourish at great cost to society as a whole.

Inside of the Abundance Paradigm a constraint inclines people to
look at creative solutions which will benefit everyone. A
win-win approach creates Partnership which enables additional
strategies. The Abundance Paradigms suggests that creativity is
an inexhaustible resource which can find solutions which benefit
everyone.

The relative wealth and prosperity of people today compared to
past generations is primarily a result of the modern habit of
developing and sharing knowledge which is part of the expansion
of the Abundance Paradigm in the evolution of modern cultures.

You can see these differing Paradigms produce different outcomes
in the dealing with resource scarcity. What examples can you
come up with from your own experience?

Now consider how many countries and regions have tremendous
poverty despite being blessed with abundant mineral wealth, e.g.
abundant fossil fuels deposits. A few countries, e.g. Norway
have used such resources to benefit everyone and invest in a
sustainable future. Different Paradigms can actually /create/
material scarcity even when the underlying resources are
plentiful. Where can you see examples of this in your own
experience?
