* Productivity is Unlimited

The visionary entrepreneur is in a creative engagement with what's
possible.  They are limited by their current resources and the
environment in which they're trying to fulfil their vision.  At any
given time, much of their vision is out of scope and they're
constantly looking for how they might be able to bring more of their
vision into scope.  When technological advances, such as automation
become available, the visionary entrepreneur expands the scope of
their enterprise and is more likely to want to hire more employees and
to upgrade the positions of their existing employees to take advantage
of increased productivity and other opportunities from the advances.
These are classic win-win strategies leading to a higher level of
prosperity in the world at large.

The expert mba in charge of a business is in a creative engagement
with how to increase profits.  They are constantly looking at how they
can reduce their overhead.  When technological advances, such as
automation become available, the mba takes advantage of reducing their
work force, letting go of all the employees whose labor is no longer
required.  This increases profits to sharholders as well as creating
the possibility of an expansion of their business by undercuttin their
competitors.  If their competitors can copy this strategy they may
maintain their market share, and similarly be able to reduce their
work force.  Otherwise, the competitors will be laying off workers
because of their reduced market share.  Opportunties for consolidation
by acquiring competitors may become available.  These are all classic
zsero-sum (actually win-lose) strategies.
