* Abundance and Partnership as Contexts

** What do we mean by Abundance, etc. here?

Human Beings are social creatures who
- Grew Up In and Inhabit one or more Societies

All Societies have a Culture
- a Giant Shared Context (aka a Paradigm)
which shapes the lives of everyone in the Society
- often (usually!) without them recognizing that shaping!

We're distinguishing Abundance as a Social Context
- a Context for how you live your life
- and especially as you interact with others!

We don't mean Abundance in the sense of
- Having plenty of whatever you want!

Please read the [[file:Presentations/robin-and-chris-abundance-parable.org][Robin and Chris Parable]] before proceeding!

** Abundance Resources

Please see

- [[file:RESOURCES.org][Resources on Abundance and Partnership Context]]

** Diverse Viewpoints on Abundance Aligned!

Please explore this remarkable table

- [[file:abundance-vs-scarcity.org][Abundance Culture vs. Scarcity Culture]]

which shows the alignment of
- Partnership vs. Dominator Culture (Riane Eisler)
- Abundance vs. Scarcity (Maslow, et al)
- Win-Win vs. Win-Lose (Game Theory)
- and more!

The alignment of these different perspectives improves our
understanding of and our ability to effectively deal with Scarcity
Contexts which get in our way.

 ** A Few Additional Notes

Social Contexts are made of Memes!
- please read this [[file:meme-definition.org][Meme Definition]]

We believe that subjecting almost all children to 13 or more years of
Dominator-Paradigm "Education" is harmful to them and to society as a whole.
There are many alternatives which have demonstrated their superiority, including
- https://en.wikipedia.org/wiki/Montessori_education
- https://en.wikipedia.org/wiki/Mastery_learning

and the authors of this website invite your attention and possible
participation with
- [[https://gregdavidson.github.io/loel/][The League of Extraordinary Learners]]
a Learning Community that's just getting started.
