* Abundance and Partnership as Contexts

** What do we mean by Abundance, etc. as Contexts?

Human Beings are social creatures
- We Grew Up In and Inhabit one or more Societies

All Societies have a Culture 
- a Giant Shared Context (aka a Paradigm)
which shapes the lives of everyone in the Society
- often (usually!) without them recognizing that shaping!

Abundance and Partnership can be part of a Social Context
- shaping how you live your life
- and especially how you interact with others!

So we don't mean Abundance in the sense of
- Having plenty of whatever you want!
although a Context of Abundance and Partnership
- Can make it more likely you'll get what you need!

Before proceeding
- please read the [[file:Presentations/robin-and-chris-abundance-parable.org][Robin and Chris Parable]]

** Abundance Resources

Please explore our

- [[file:RESOURCES.org][Resources on Abundance and Partnership Context]]

and we invite you to suggest others!

** Diverse Viewpoints on Abundance Aligned!

Please explore this remarkable table

- [[file:abundance-vs-scarcity.org][Abundance Culture vs. Scarcity Culture]]

which shows the alignment of
- Partnership vs. Dominator Culture (Riane Eisler)
- Abundance vs. Scarcity (Maslow, et al)
- Win-Win vs. Win-Lose (Game Theory)
- and more!

The alignment of these different perspectives improves our
understanding of and our ability to effectively deal with Scarcity
Contexts which get in our way.

 ** Abundance and Partnership in Education

The U.S. education system was heavily influenced by the 19th-century
Prussian model, adopted in the 1830s-1850s to create a standardized,
state-run system aimed at fostering obedience and conformity, it
introduced compulsory attendance, age-based sorting, factory-style
bells, and strict, teacher-led, standardized instruction.

Many other countries have adopted similar systems.  We believe that
subjecting almost all children to 13 or more years of this
Dominator-Paradigm "Education" is harmful to them and to society as a
whole.

There are alternative education systems which are consistent with a
partnership model and have demonstrated their superiority in terms of
educational achievement, including
- https://en.wikipedia.org/wiki/Montessori_education
- https://en.wikipedia.org/wiki/Mastery_learning

If you're interested in Partership Education outside of institutions,
we invite your attention and participation with our new Learning
Community:
- [[https://gregdavidson.github.io/loel/][The League of Extraordinary Learners]]

** Grounding the Etherial

Contexts are material.  They are made of memes!

Please read this concise [[file:meme-definition.org][Meme Definition]]!

You can understand a society by observing the memes being presented
and exchanged in that society.

You can understand yourself better by noticing the social memes which
you've internalized and which are shaping your awareness and behavior
- generally without you noticing the foreign influence!
