* UBI: Universal Basic Income and Universal Prosperity

** The Problem: Inequity and Exclusion

*** We Want All People To Win

One of the serious humanitarian failings of our world is Economic and
Social Inequity and the exclusion of many people from access to both
necessary and important resources based on their economic and social
status.

We are aware that people do not meet, and should not have to meet all
or even most of their their needs through monetary transactions!  Some
of the suggestions here are for optimizing UBI and others are
suggestions for making human needs more affordable.  In other places
we discuss less transactional ways of meeting human needs and we must
trust that you understand that here we're only addressing some aspects
of the goal towards all people sharing in the abundance of the modern
world.

*** Developed Countries vs. Developing Countries

We're also aware that while many people in many developed countries,
and especially in America are recently experiencing that inequity is
increasing, data shows that in the world as a whole inequity is
decreasing!  But these phenomena are coming from very different
baselines.

People in many developed countries who are middle-middle class or
lower are experiencing a significant fall in prosperity, economic
security and civil rights for the first time in two generations.  For
Americans it's more like three generations, since the end of World War
II.  What makes this especially raw is observing richer people in
their countries becoming richer faster than ever!

In contrast, the median person in the developing world has seen
prosperity, economic security and civil rights improve enormously over
the last generation while inequity has decreased.  While this is truly
a change worth celebrating, it's worth noting that the higher level
the median person in the developing world has now reached is still
much lower than the level experienced by people considered just above
the poverty level in the developing world.

These trends lead those of use privileged enough to live in the developing world to ask:
- Will median conditions in developed countries continue to go down?
- Will this evil trend stop progress in developing countries?

*** What Can Help People In The Developed World? UBI?

And now that we may be nearing the end of the extreme right-wing power
grab in the politics of the US and a few other developed countries, we
are starting to ask:
- Is there anything we can do to make things better?
- But by "we" we usually mean what "better politicians" can do.
- Even though we increasingly distrust and despise all politicians!
- Most of us are feeling powerless!

One of the most popular ideas for solving all of these problems is
UBI: A Universal Basic Income.  While everybody would get it, UBI
would raise the economic conditions of those on the lower-end of the
economy a lot.  As UBI was delivered to people enjoying higher
economic levels, UBI would make less and less difference and more and
more of it would wind up being returned as taxes.  Thus in addition to
helping the most needy, UBI would reduce inequity.  Sounds perfect,
right?  Well, we know not to take such things for granted!

There are various forms of UBI.
- Could some of them work as well as we'd like?
- What other things might help?
- Could the best forms of UBI synergize with other solutions?

** Inequity Often Precludes Meeting Basic Needs

Despite either
+ working vary hard at jobs which society needs
+ or being unable to do so
  - including children and the disabled
many people lack the resources to
+ meet their Basic Needs
  - Food, Water, Security, Shelter, Transportation, Heath-Care
+ enjoy potentially abundant material comforts
  - access to information
  - useful mass-produced goods
+ or modestly access the skills of others in the form of services and
  specialty goods which would make a big difference in the quality of
  their lives and the lives of their families.

This problem is happening despite all of these needed resources being
so abundant in the modern world that the world as a whole could easily
afford to meet all of these needs for everyone, and if that access
were done intelligently, the world (the median individual and the
collective measured by, e.g. the GDP) would be richer as a
consequence. A win-win is very possible!

The inequity is a result of artificially created scarcities.

** What Universal Equity Might Look like

1. Access to a highly effective basic education including
- fundamental skills
  - native skill in one or more prestige languages
    - including native literacy in that or those languages.
  - proficiency with
    - the requisites for most valuable skills
    - the requisites for participating as a first-class citizen
    - learning how to learn
  - a map of all human knowledge, so that they can
    - select marketable skills they find interesting
- proficiency in some of their chosen marketable skills
2. Access to social "insurance" or "safety nets" to protect against
   inability to meet their needs through trade.
- Sufficient to meet the needs of children and the disabled
  - respecting their dignity, their inherent worth as human beings
  - including their participation in society

** Designing a Practical UBI

It wouldn't work to give everyone the same UBI!

People's life situations can impact the nature and costs of meeting
their needs
- Healthy working-age people with marketable skills they enjoy
- Children
- People with (hopefully) temporary illnesses
- People with chronic disabilities
- People live in places with very different costs of living!

A practical UBI needs to consider these different life-situation.

Different needs have very different cost-structures
- Where someone lives can have a huge impact on the cost of
  - Food, Water, Security, Shelter, Transportation, Heath-Care, etc.
- Various forms of these goods and services might be available
  1. for purchase, sometimes with subsidies
  2. for "free" - government provided, paid for by taxes
  3. in a managed and subsidized marketplace

UBI can help with 1. and 3. but it will have to track their different
costs to people in different life-circumstances as well as those
living in different places.

** UBI COL: Cost of Living by Location Index

The US Military deals with this issue routinely.  They maintain an
Index of the COL in different areas where they post their service
members to suitably cover their living expenses.

This indexing system needs to be adjusted progressively for people who
have a lot of choice in where they live.  It won't work if everyone is
maximally rewarded if they move to the places which have the highest
COL!

A practical system would adjust the UBI COL progressively such that
- it's purchasing power is always a bit higher where the COL is a bit
  lower, i.e.
- individuals and families depending only on the UBI can afford a
  materially nicer lifestyle if they choose locations with a lower UBI
  COL.

Employers would, as now, be free to offer more compensation to attract
needed workers to more expensive areas.

Local governments policies may add incentives which will draw
employers, individuals and families to their regions.  Such policies
must avoid directly or significantly maintaining or creating
inequities.

** How Could UBI Fail?                                                                                        

One of the biggest threats to UBI being successful is if it simply
raises prices by the amount of the UBI.  People then wind up paying as
much to meet their needs, plus paying some amount of the taxes which
support the UBI.  So far UBI to work, we have to address the runaway
costs which make things unnecessarily expensive.

What happened to fast food workers in California?
- In 2004 their minimum wage was rasied to $20!
- Since then inflation has made them poorer than ever!

** The Cost Of Living Keeps Rising!

Americans are currently experiencing
- a massive increase in the cost of living
- house prices, mortgages and rents are all climbing
- used cars are as expensive as new cars were recently
- new cars are only affordable by a few
- Obamacare's Healthcare Protections are being rolled back.

Median income Americans are finding it hard to make ends meet.
- Most young people no longer expect to own homes.
- People are struggling with rents and transportation.
- People are losing their healthcare without subsidies!

If you think something's wrong, you're right!
- Prices should be going down, not up!
- Wait, how can that be?

** Increased Experience Lowers Costs, Increases Quality

In a healthy economy, the costs of goods and services tend to go
/down/!  A major reason for this is the Experience Curve Effect.

With experience, providers of goods and services discover ways that
they can both
- increase quality
- decrease costs
and in a competitive market they should be doing both!

** The Consumer's Movement

[[https://en.wikipedia.org/wiki/Consumer_Reports][The Consumers Union]], publisher of Consumers Reports was founded in
1936 as an industry-independent not-for-profit dedicated to informing
the American public about the quality and safety of industrial
products.  Then as now, industry wasn't eager to have people shopping
for their products aware of issues with those products.  The Consumers
Union was often treated poorly by government, including being found to
be a "Subversive" organization by the infamous [[https://en.wikipedia.org/wiki/House_Un-American_Activities_Committee][House Un-American
Activities Committee]]!

World War I, the worldwide Great Depression and World War II left the
US in a good position to dominate worldwide manufacturing and it
seemed to make American industry complacent.  But slowly higher
quality goods and sometimes cheaper goods started being imported from
Europe.  But how were American's supposed to tell if these unfamiliar
products were any good?

More and more Americans were reading Consumer Reports and finding out
about quality and safety issues with American products.  For the most
part, US industry ignored quality issues, but public concern about the
safety issues forced government action and American products became
noticeably better.  But the European products were getting better too,
and then some very competitive products started arriving from Japan.

Japan was highly impressed with the work on 

US and Worldwide became more and more influential and by the 1970s the
US had a vigorous "Consumer's Movement".  This led to some increase
in the quality of American products and an enormous increase in their
safety.

At the same time the US more and more goods were being shipped into 

** Quality Management
** Cars were getting better and cheaper - until

The quality of American automobiles has often been called into
question, from Ford (Fix Or Repair Daily) [[https://en.wikipedia.org/wiki/Ford_Model_T][Tin Lizzy]] to Ralph Nader's
critique [[https://en.wikipedia.org/wiki/Unsafe_at_Any_Speed:_The_Designed-In_Dangers_of_the_American_Automobile][Unsafe at Any Speed: The Designed-In Dangers of the American
Automobile]].



popular as the "Consumer's Movement" gained steam in the 19

In the 1970s the quality of Japanese cars kept increasing without the
cost increasing.  By 1980 Japan surpassed the worldwide sales of the
up-until-then dominant "Big Three" US automakers.  The "Big Three"
started having to lay off workers.  Japanese cars started
"threatening" (I would say blessing) the US automobile market.  In
1981 Ronald Reagan negotiated a "voluntary" reduction in Japanese cars
offered for sale in the US.  What then happened?

Over the next few months the cost of cars - the same cars - doubled.
But the Japanese reduced the number of cars by stopping supplying
their lower-end models.  And then then started increasing the quality
of their higher-quality cars, making them even higher quality -
without increasing their cost.  Soon Japanese cars began to be seen by
all but the most "patriotic" of Americans as of higher-quality than
cars in the US and 


cars were became more and more popular in the US until by 1980 they

** A Market for Quality
** Houses Should Be Much Cheaper Now!

I grew up in a beautiful custom-designed house which my parents were
able to have built on a large piece of property in a desirable
neighborhood with a mortgage which they could afford, which in those
days (1956) meant 1/4 of one wage earner's salary.  And that meant my
father's salary.  He had just started a job as a junior engineer, with his
salary at a minimum level.

At that time there were no power tools, so much more construction
labor was increased compared to today.  There were no "undocumented
laborers" to be exploited in our area at that time.  Sheetrock didn't
exist yet as a substitute for wood and concrete walls.  Laminates
didn't yet exist for flooring.  There were no manufactured modules for
windows or doors - everything was custom.  My parents required very
high-end construction materials and building techniques.

Now that houses of a comparable size are built with a fraction of the
labor using much cheaper materials and manufactured modules which
should be much cheaper than custom materials - the quality of
construction has gone way down and it takes at least half of the two
professional salaries to pay the mortgage!

Why are new houses so expensive?

A common answer is: Land prices have gone up!  But they haven't gone
up that much.  And if you look at the cost of rebuilding after, e.g. a
fire, on land you've already paid for, it's once again through the
roof!

** Regulating Costs

- Making things available for individual purchase maximizes individual
  choice.
- Managed marketplaces, e.g. for health insurance plans, preserves
  some individual choice but not all options some people might prefer
  or need.
- Free services generally provide the least choice.
  - Few people wish to directly pay for
    - Police and Fire
    - Roads
    - etc.

Free, Managed and Subsidized goods and services tend to reduce
individual choice in service of the Common Good.  For example,
- Municipal water might not meet some people's standards.
- Food Stamps won't cover many products.
- Cheaper Health Insurance plans might not cover treatments considered
  controversial which some people might desperately need.
  
This reduction of choice for the "Common Good" can be fine if there
are alternatives.
- It's necessary for society as a whole to avoid subsidizing things
  which are controversial, e.g. expensive health treatments which have
  not been proven to be effective when conventional treatment seems
  sufficient.
  - But there needs to be quick reconsideration of alternatives when
    someone's health is failing and the "standard" treatment is not
    working!

Because UBI, subsidies and "free" goods and services are ultimately
being aid for by our taxes, we can all be made poorer when prices are
manipulated to be high rather than lowered through continuous
improvement of processes in a healthy marketplace.

A helpful way to increase the beneficial impact of goods, services,
subsidies and regulations enacted by government legislation is to
require that all government legislation include a [[https://en.wikipedia.org/wiki/Sunset_provision][Sunset Provision]]:
- The legislation must clearly state the problem it is intended to
  address, how what it is requiring is expected to solve or ameliorate
  that problem along with any anticipated possible side-effects.
- It must also enable ongoing objective measurement to track how well,
  if at all, it is making the intended difference, with what
  side-effects and how such results are to be interpreted to show
  whether the legislation was successful or unsuccessful.
- The legislation must come up for periodic review at which time the
  results of the measures of its effectiveness must be shown and
- It will then need to be re-authorized by a new vote or it will
  cease.
- It's also ideal if parties affected by the legislation, including
  taxpayer groups, can sue to reverse any re-authorization in the case
  where it was shown as being unsuccessful or where the measurement or
  interpretation can be shown to be fraudulent.
  
** The Rich Keep Getting A Bigger Piece of the Pie

[[https://www.epi.org/productivity-pay-gap/][US Productivity has grown massively since World War II]]
- Until 1980 it made all American's richer
- Since 1980 (Ronald Reagan) it went to the Rich

The Rich Are Getting Richer Faster!
- Upper middle class people have gotten richer
- The top 10% have gotten much richer
- The top 1% even richer still!
- Billionaires are the new Millionaires!

The Lower-Middle and Middle-Middle Class has shrunk.

UBI might only bring everyone below the median level to the same level
of poverty.

How can we ensure that productivity gains enrich everyone?
- And can we claw back the lost gains?

** Universal Effective Education

Much of the existing publicly-funded education system produces a
Bell-Curve distribution of outcomes.

Alternative systems, e.g. Montessori and Mastery Education, produce an
outcome distribution with a much higher level of educational attainment.

Bell-Curves are the typical result of processes with an essentially
random process.

Educational resources need to be vetted for being effective for all students.

Accepting educational systems which don't work because they're
generally ineffective or too one-size-fits-all rigid is simply
unacceptable.

Any educational system which
- resists being objectively measured
- doesn't clearly work well for essentially all students
- should be immediately cut off from all funds!

In Japan, elementary school students are not socially promoted because
they are not allowed to fall behind.  Instead, when a student is
starting to fall behind they are given additional instruction from
special teachers trained in overcoming the child's learning
difficulties.

Ideally all schools would
1. ongoingly study the techniques used in the most successful schools
   in the world and
2. learn how to adopt those methods for their specific populations and
3. provide alternatives and enrichment for those students who need it.

"No child left behind" should be the practice, not a slogan!

Even better than bringing in supplementary 
- doesn't immediately correct their processes when the results are
  substandard, such as by
  - bringing in sufficient supplementary resources to meet the needs
    of current students
  - while studying and adopting better alternative methods

** Languages and Literacy as Examples

Young human beings naturally learn any language in their environment
to native proficiency, by immersion.  Trying to teach languages
top-down, e.g. by presenting vocabulary and grammar rules to be
memorized, is absurdly inefficient and ineffective.  If you want
bi-lingual (or multi-lingual) schools, make sure that the school
environment immerses the students in the languages you want them
learn - both inside and outside of the classrooms.  An especially evil
practice is providing "separate but equal" mono-lingual instruction as
accommodation for primary or secondary school students who don't speak
the languages which would benefit them the.
- [Link required for details.]

Note that a learner's native dialect SHOULD NEVER BE INSULTED!  Any
linguist will tell you that a local dialect is not objectively
inferior to a national dialect.  It's just that having fluency in the
national "prestige" dialect gives a person desirable advantages.  Sell
the advantage of knowing both without insulting them or their local
culture or local dialect!  Then teach the most useful languages and
dialects through immersion.

The best way to learn to read is the same way as to acquire
spoken-language skills: Immersion through lots of exposure.
- A child has materials they like read to them by a favorite family
  member with the reading materials at a comfortable viewing distance.
- This should start as soon as they're able to follow stories.
- This method can work for dyslexic children too, it just takes
  longer.
- [Link required for details and alternatives.]

The best way to learn to read well is to encourage and facilitate
learners finding diverse and progressively more sophisticated
materials WHICH THEY LIKE and which they'll happily read.  Note that
this is the design of the Harry Potter series - not that this series
will be the right one for all students!  Also note that in Japan it's
completely acceptable for people of all ages to read comic books.  An
all too common experience of American children is for educators and
other adults to insult them for what they like to read and to require
them to read things they don't like.

The best way to learn to write well is to engage in lots of social
online writing with much of it visible to all of their peers.  Online
writing coaches would provide enrichment by showing how to make the
writing communicate better without insulting the original expression -
yes, the coaches require training to do both of these things, and
their effectiveness needs to be measured!  It's natural to want to
communicate effectively, so when people are assisted in doing so
without being judged or insulted, they are eager to improve!

But school learning can also work, for example:

Despite having the same levels of dyslexia as American children,
nearly 100% of Japanese children come out of elementary school fully
literate in four writing systems
- Romanji :: the alphabetic system used by English and most of Europe
- Kanji :: the ideographic Chinese system with over 5000 characters
- Katakana and Hiragama :: two syllabaries customized for Japanese
  phonetics.
How do they do this?
- They instill a love of learning which is far less present in American classrooms.
- When a child starts to fall behind, they immediately bring in
  supplementary teachers with training in overcoming common learning
  disabilities.
  
As with all sophisticated processes:
- There are several methods which efficiently and effectively produce
  fluent literacy.
- There are far more methods which work poorly or not at all!

** Universal Access to Knowledge

Much of the world tries to make all human knowledge available in public
libraries.  All human knowledge is rapidly moving online and most
human beings now have on-line access.

How do we make this better?

1. Make Internet Access available to everyone, everywhere!
   - The high cost of Internet Access in some places is an artificial scarcity.
     - Internet Access with sufficient bandwidth for access to
       educational materials and on-line jobs can be provided very
       inexpensively everywhere, e.g. by community mesh.
     - Quality PCs as well as tablets and smart-phones with good
       screens and keyboards are now also sufficiently inexpensive
       that decent-quality units can be made affordable to everyone.
2. Revise Copyright and Patent law so that they maximize access to
   knowledge without disencentivizing content producers.
   [Details to come!]

** Universal Healthcare: We can do better!

Currently governments pay for most of the cost of the development of
medical tests and treatments and also pay most of the cost of
providing tests and treatments to their citizens.  This is true even
in America where (first) the government pays more per-capita than any
other country for healthcare, and then (second) American citizens pay
more than any other country per-capita in the form of "health
insurance"!

Many tests and treatments are priced so high that many people cannot
afford them and they either go without or have to make due with
inferior substitutes.  This is justified as being necessary because
of the patents which allow companies to afford the development of
these tests and treatments.  But a patent is just a legal monopoly and
we know that monopolies make things more expensive and less available!
So what can we do instead?

** Bounties instead of Patents

In a Bounty System, participating governments jointly post how much
they will pay - as a lump sum - for desired medical advances.  The
Bounties are nuanced, e.g. they're highest for advances which are more
effective, cheaper to manufacture or deliver, etc.  All final tests of
purported advances must be verified by extensive independent tests
before the Bounty will be paid.  Once the Bounty is paid, these tests
and treatments are available patent-free to the citizens of the
countries whose governments funded the bounties.  These advances are
now generics which companies can complete for making at the lowest
cost.

** Double-Hybrid AI

This material coming soon.

- Reference Mycin
- Hybrid systems available for free to everyone 24/7.
- Tests available cheaply for everyone!
  - Recommended tests free.
  - Extra tests at cost.
- Followups by Nurses and Physicians for anything serious!

** Incremental Training of Healthcare Professionals

Instead of separately training different classes of healthcare
professionals, with the greatest prestige and student debt assumed by
doctors, let the normative path be incremental:

- Interns (unprofessional short-term entry points)
- Orderlies and Nurses Assistants
- Nurses and Technicians
- Knowledge-Intensive Nurse and Technician Specialties
- Nurse Practitioners
- General Practice Physicians
- Specialist Physicians

Provide on-the-job training any of these professionals to move forward
to any other specialty where there is unmet demand and they have
sufficient experience and show sufficient competence.

Everyone staying in any of these jobs should also be getting
on-the-job updates as knowledge of their specialty advances.

Ensure regular and reasonable hours with their job plus their added
training.  Exhausted or compromised healthcare workers are as
unacceptable as exhausted pilots!

The impact of all interactions with Patients needs to be measured and
fed back into the training of all of the professionals providing care.
As experience and ongoing training improve outcomes, they should get
increases in their salaries.

If an upgrade to a more knowledge-intensive specialty winds up not
working for someone and/or they are not providing acceptable patient
outcomes, let them go back to their previous specialty without
judgment.

Results:
1. No student debt.
2. No extreme academic competition.
3. Lack of 1. and 2. allows doctor's salaries to be more reasonable.
4. More healthcare professionals in the needed roles.
5. No one doing a job they don't feel a calling for.

Note: This doesn't need to be the only way for people to get trained.
There can still be some schools which provides scholarships for
extremely gifted students who want to become physicians - and maybe
such people should be encouraged shoot higher, e.g. to be
MD+Ph.D. research physicians.
