* Abundance vs. Scarcity - A Parable

Our characters are Robin and Dana.

Robin lives comfortably thanks to family money, enough that Robin will never
need to work. Robin has a liberal arts education from a prestigious school.
Robin travels in Arts circles and is often involved with projects with arts
funding organizations and prestigious exhibitions. Robin once dated an artist
leading to a tumultuous but brief marriage. Robin is grateful for the prenuptial
agreements suggested and drawn up by the family lawyer. Robin now only dates
other people Robin considers to be of similar station in life.

Dana is an entrepreneur. Dana had an up-and-coming technology business which was
destroyed by the tech crash called the dot bomb. Dana then created a new
non-tech business, using their home as collateral. The new business was doing
very well until Covid hit and destroyed it's business model. The result is that
Dana is now homeless and penniless. Dana is in an exciting conversation with
some fellow entrepreneurs, friends and former colleagues about new possibilities
while living rent-free in a spare room happily provided by one of them.

Abundance is not about having lots of stuff. It's a context. Which of our
characters are living in Scarcity? And which of our characters is living in
Abundance?
