* Abundance vs. Scarcity - A Parable

Our characters are Robin and Chris.

Robin lives comfortably thanks to family money, Robin will never need
to work. Robin has a liberal arts education from a prestigious school.
Robin travels in Arts circles and often influences which artists get
access to resources.  Robin once dated an artist.  They had an
exciting but brief marriage. Thank goodness the family lawyer advised
Robin to have them sign prenuptial agreements!  Robin no longer dates
anyone of a lower station in life.

Chris is an entrepreneur. Chris had an up-and-coming technology
business which was destroyed by the dot bomb. Chris then created a new
non-tech business, using their home as collateral. The new business
was doing very well until Covid destroyed it's business model.  Chris
is now homeless and penniless. Chris is in an exciting conversation
with fellow entrepreneurs, friends and former colleagues about new
possibilities while living rent-free in a spare room happily provided
by one of the other entrepreneurs.

Abundance is not about having lots of stuff. It's a context. Which of our
characters are living in Scarcity? Which of our characters is living in
Abundance?
