* Abundance and Burning Man

I'd like to talk a bit about /Burning Man/ - partly because it
has informed my understanding of Abundance and partly because
Burning Man is so much fun to talk about! Burning Man was
started by the San Francisco /Cacophony Society/, as a way to
become more conscious, more aware of the assumptions programmed
into us by our /Default Culture/, the culture (or cultures)
which have surrounded us as we've grown up, at school, at work,
as we play, as we socialize, etc. /Default Culture/ gives us
much of our largely unexamined understanding about the world,
human beings and our own nature.

/The Cacophony Society/ led /to Burning Man/, whose
participants, called /Burners/, have created a worldwide and
diverse /Culture/. /Burners/ have a lot of great language for
talking about culture. I especially like the term /Default
Culture/ because it acknowledges pre-existing culture without
putting it down. Nearly everyone understands that existing
societies and their cultures are badly flawed, but the biggest
problems go away when you (first) become /aware/ of how our
mainstream or traditional /Default Culture/ influences us and
(second) realize that it's only a /Default/ - that you are free
to create alternative cultures and live the most important parts
of your life inside of the /Context/ and /Culture/ which you
co-create and which you choose.

/Burners/ have a tradition of adopting playful nicknames, which
often become their preferred new names. At an early Burning Man
event I received the nickname "Heart-Touch" or simply "Touch".
On my website I explain some practical reasons why nicknames can
be useful in a world of Social Media. But let me explain why I
like this name so much. I grew up as an "in my head", "geeky
guy", with an intellectual explanation for everything and heavy
criticism for anything I didn't like. Being a thinking person is
still very important to me, but I no longer see it as
everything. As /Robert Fulghum/ said, "Don't Believe Everything
You Think!"

One of the principles of Burning Man Culture is /Radical
Inclusion/. Much of the extraordinary art at Burning Man only
possible because of collaboration between geeky engineer types
of people along with very non-geeky artist types. You can't be
all things and when you can collaborate, you don't have to be!
At Burning Man I was completely accepted and loved as my geeky
self while I was also being given rich opportunities to grow.
I'm still geeky and along the way my humanistic understanding
has grown considerably. The name "Touch" reminds me that there's
more to life and my connections with other human beings than I
can fit inside of /any/ intellectual framework. Being a feeling
person is very important to me. Being called "Touch" reminds me
of this!

Burning Man Events are very colorful, but brief. Burning Man
Culture is now present year-round in many places throughout the
world. I invite you to look up the /Burning Man Principles/ on
the /Burning Man Webiste/. The /Burning Man Principles/ are a
great introduction to /Abundance/.

One of the /Burning Man Principles/ is /Radical Acceptance/,
which is also a principle of /Abundance Culture/.

Here is how I would express two key elements of /Abundance Culture/
- Radical Acceptance :: Accepting and including people without judgment.
Accepting people exactly the way they are and accepting that they're not what
they're not. It's important to understand that this acceptance does not inhibit
people's growth into what's next for them -- in fact it tends to accelerate it!
- Unlimited Growth And Development :: There are no fixed limits to human growth
  and development, neither individually nor socially.

There's so much more I'd love to share with you about my experience of Burning
Man, but for we're done with it for now, it has served its purpose for this
conversation, so let's move on!
