* Abundance Talks

These are drafts of some component parts of some presentations
I'm planning for introducing the distinctions of Abundance to a
diverse range of potentially interested folks.

I'm planning on combining more than one of these pieces to
create each talks. I don't want the talks to be too long, so if
I'm going to cover all of this material - and probably some more
material as well - I'm expecting to need to give three to four
talks.

I'm expecting to heavily revise and even to completely rewrite
this material - and I need your feedback to do that effectively!

** Easier Pieces Ready for Feedback
   
[[file:abundance-introduction.org][Abundance Introduction]]
[[File:abundance-and-burning-man.org][Abundance and Burning Man]]
[[file:abundance-example-water-policy.org][Abundance Example: Water Policy]]
[[file:abundance-and-the-partnership-way.org][Abundance and The Partnership Way]]

** Really Needing Feedback

This is an especially rich piece and I would like feedback on
how to develop it so that interested people can get it:
   
[[File:abundance-prerequisite-distinctions.org][Distinctions For Abundance]]

** Less Ready for Feedback

[[file:abundance-and-game-theory.org][Abundance and Game Theory]]
[[file:abundance-distinctions.org][Abundance Distinctions]]
