* An Example: Water Scarcity

My family comes from Hawaii where water is never scarce, but I
grew up and live in California where the media and experts
regularly tell us that there is an impending catastrophe for the
entire southwestern of North America because of the increasing
scarcity of water.

What are some possible responses to a shortage of water? (And by
the way, everything I'm saying here could apply to any other
scarcity, not just water.)

**** A Win-Lose Approach

A popular response is for those with special access to the
resource to protect that access regardless of how that effects
others. This is the dominant response in California where the
government gave water rights to certain property owners
regardless of future availability. Those privileged rights
holders currently use inefficient irrigation methods and grow
water intensive crops. They resist any effort to conserve water
in fear of having their water rights reduced if they don't use
it all.

In many places growers with water rights have taken so much
water out of rivers that those rivers have dried up, leaving
nothing for people downstream. Other growers have pumped so much
water out of regional aquifers that the wells of their neighbors
have run dry and the very land has subsided.

Here we see the strategy of /hoarding/, an example of a
defensive /win-lose/ interaction. Hoarding is fear-driven. When
I'm afraid that there's not enough of something to meet my
needs, I may try to hoard it, and/or to acquire or maintain
privileged access to the resources at the expense of others. If
I have direct power, I may take the resource from others by
force. If I have political power I can have the government exert
force on my behalf.

**** Win-Win

At Burning Man I was talking with some new friends from Israel
about our water problems. (No, we're not going back to talking
about Burning Man now, that just happens to be where I often
meet people and have interesting conversations!) These new
friends expressed amazement at how inefficiently we use water in
the US. Apparently they grow the same crops in Israel as we do
in California, but with /less than a tenth of the amount of
water!/ If farmers in the arid parts of North America used water
as efficiently as Israeli farmers do, there would be no
shortage, even in drought years. How do the Israeli farmers do
it, and why?

American water policy was formed during a time when more water
was available and when government was persuaded to build canal
and reservoir systems to redistribute a great deal of water from
the northern parts of the country where it was plentiful to the
arid southwest. As agriculture in the southwest expanded and
became a politically powerful coalition, more water was diverted
until it began to stress the once-plentiful Northern rivers,
leading to the current political stalemate or a supply-side
solution.

Israeli water policy began when visionaries were faced with
trying to create an agriculturally self-sufficient new nation in
an area that didn't have enough water anywhere to do what they
wanted using conventional irrigation. Israelis never viewed
water as plentiful. Israelis knew that they had to pursue water
efficiency as much as possible. Israeli farmers deployed
efficient drip-systems many years ago. More recently they have
deployed high-tech systems which measure the exact water needs
of each plant and allocate water accordingly. Israelis expect
their government and institutions to create more efficient ways
to use water and to create incentives for farmers to use those
methods. And indeed, they are actively pursuing promising ideas
of further significant efficiencies, such as advanced
greenhouses, aeroponics, etc.

Inside of the Scarcity Paradigm, a constraint, such as the
shortage of a resource, inclines the powerful to follow a
Dominator Approach, adopting win-lose strategies to allow them
to survive or even flourish at great cost to society as a whole.

Inside of the Abundance Paradigm a constraint inclines people to
look at creative solutions. The Abundance Paradigms suggests
that creativity is an inexhaustible resource which can find
solutions which benefit everyone.

The relative wealth and prosperity of people today compared to
past generations is primarily a result of the modern habit of
developing and sharing knowledge which is part of the expansion
of the Abundance Paradigm in the evolution of modern cultures.
