* Abundance Culture Introduction 2

** The World Has Changed

This is a special and wonderful time to be alive.  For thousands of
years great thinkers have pondered important questions such as:
- What is Life?
- What is Human Nature?
- and How Can We Lead Great Lives?

Until recently, the answers of the greatest thinkers were little more
than unquestioned tradition or individual speculation and opinion.
But that didn't stop them from endless arguing about who was right!

But the world has changed! Radical new ideas have emerged from the
sciences.  Radical old ideas have emerged from diverse cultures which
were unfamiliar to one another before our modern global culture
brought them together.  As these ideas are gradually absorbed and
integrated, new ways of thinking and understanding emerge.

** A New Viewpoint Is Emerging

I see a particularly exciting view emerging which I'd like to share
with you.  It's important to acknowledge that what I'm going to
present is intended to be one useful model or viewpoint on these
important matters, not the only valid or useful model or viewpoint.  A
characteristic of modern thinking is the use of multiple models and
viewpoints to aid in understanding subtle topics.  Therefore, you
don't initially need to integrate this new view with your existing
understandings - that can come later.  Initially I'd like you to
listen for what the new ideas are and to look for what clarity and
insight this new viewpoint can provide on matters which are important
to you.

I'm going to introduce you to a rich and powerful viewpoint which I'm
going to call /Abundance Culture/.  Another term for it is the
/Abundance Paradigm/, but for now, let's avoid that fancy term!
Abundance Culture is a synthesis of the work of many great thinkers,
including people like Riane Eisler and her model of Partnership
Culture, Marshall Rosenberg with his model of Compassionate
Communication and the great 20th Century mathematicians who developed
Game Theory which clarifies the fundamental difference between
Cooperative or Win-Win interactions vs. Competitive or Win-Lose
interactions.  Please see our website for a more complete list of
sources, and feel free to point out any which we've missed!  But for
now, let's move on!

** It's A Big Idea!

The next thing to clarify is that /Abundance Culture/ is much bigger
than a Culture of Material Abundance, i.e. a Culture where /people
have lots of stuff/.  Abundance Culture addresses all human needs,
including Material Needs such as health, security and comfort and
non-material needs, such as Freedom, Respect, Self-Expression,
Connection and Meaning.  And /Abundance Culture/ is a Culture, so it
includes our relationships with others and how to ensure that our
strategies for getting our needs met synergize rather than interfere
with one another.

/Abundance Culture/ 

** STOP HERE!

** Game Theory
Consider the concepts of win-win.

** Partnership

Abundance Culture is an understanding of the power of human beings when we're
acting
- transparently
- creatively
- and in partnership.

** The Culture of Science

One of the greatest examples of Abundance is the extraordinary success
of doing science transparently in public, a tradition which began with
the thinkers of the 18th Century Enlightenment who were also the
founders of

** Fragments

The great breakthroughs in science 

Scholarly developments such as
- Game Theory
- Meme Theory
- Evolutionary Psychology
- a modern worldview

Radical traditions such as
- Zen Buddhism
- the 18th Century European Enlightenment

Over the last few decades a number of fundamentals We are fortunate to live in a time when much of the confusion about
fundamental matters has been clarified.  We have a better idea than
ever before of what exactly we don't understand!  Yes, this is really
important!  And we have a better idea of what the things we /do/
understand actually are!  I want to talk about one of the Big Context
things we have recently come to better understand, something which I'm
going to call Abundance Culture.

