#+OPTIONS: toc:nil num:nil html-postamble:nil
* Some Notes on *Abundance Culture*

This web site is moving to [[https://github.com/TouchPuuhonua/Abundance#readme][My Github Abundance Repository]], which I invite you to
explore even as it is undergoing redesign and reconstruction!

One of the largest and most important shifts taking place in
the world today is the gradual shift from Scarcity Culture
to *Abundance Culture*. Our culture directs and often limits
our lives, especially when we are largely unaware of its
influence and structure.

** Some *Abundance Culture* Links

[[file:who.org][My Participation with *Abundance Culture*]]
	 
[http://puuhonua.org/abundance/abundance-vs-scarcity.html][Abundance vs. Scarcity]]

Many groups, organizations and communities are actively
expanding *Abundance Culture* in their own unique ways.  Here
are a few [[http://touch.puuhonua.org/orgs-human.html][Links to Humanistic Organizations]]

Everyone acknowledges the vital importance of education, we
Americans spend enormous amounts of resources on it, our
teachers tend to be very committed and hard-working so
[[http://ngender.net/loyl/loyl-paradigms.html][What's Undermining Education?]]  This is a good example of the
power of paradigms in shaping thought and action.

My Website: http://touch.puuhonua.org
